#!/usr/bin/env python3
"""Regenerate the README plugin table from .claude-plugin/marketplace.json.

The table between the PLUGIN-VERSIONS markers is DERIVED data. Hand-maintaining
it is why five version cells and the whole plugin list had drifted: the Update
Versions workflow stages only marketplace.json, so nothing ever rewrote the
README. This script makes marketplace.json the single source of truth for both
the versions AND which plugins are listed.

Usage:
    python3 scripts/render_readme_table.py            # rewrite README.md
    python3 scripts/render_readme_table.py --check    # exit 1 if it would change

Exit codes:
    0 - README already matches (or was rewritten)
    1 - --check found drift, or an input was missing/invalid
"""

import argparse
import json
import sys
from datetime import date
from pathlib import Path

START = "<!-- PLUGIN-VERSIONS-START -->"
END = "<!-- PLUGIN-VERSIONS-END -->"


def cell(text: str) -> str:
    """Escape a value so it cannot break out of its markdown table cell.

    A literal `|` in a description would silently add a column and shift every
    later cell, so it is escaped rather than trusted. Newlines collapse for the
    same reason.
    """
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def repo_url(plugin: dict) -> str | None:
    """Prefer the explicit repository URL; fall back to the github source."""
    url = plugin.get("repository")
    if isinstance(url, str) and url.startswith("http"):
        return url
    src = plugin.get("source")
    if isinstance(src, dict) and src.get("source") == "github" and src.get("repo"):
        return f"https://github.com/{src['repo']}"
    return None


def render(plugins: list[dict]) -> str:
    lines = [
        START,
        "## Plugin Versions",
        "",
        "<!-- GENERATED by scripts/render_readme_table.py from .claude-plugin/marketplace.json — do not edit by hand. -->",
        "",
        "| Plugin | Version | Category | Description |",
        "|--------|---------|----------|-------------|",
    ]
    for p in sorted(plugins, key=lambda x: x.get("name", "")):
        name = cell(p.get("name", "?"))
        url = repo_url(p)
        label = f"[{name}]({url})" if url else name
        # "developer-tools" is the manifest's slug form; the table shows prose.
        category = cell(p.get("category", "")).replace("-", " ").replace("_", " ").title()
        lines.append(
            f"| {label} | {cell(p.get('version', '?'))} | {category} | {cell(p.get('description', ''))} |"
        )
    lines += ["", f"*{len(plugins)} plugins · last generated: {date.today().isoformat()}*", "", END]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    ap.add_argument("--check", action="store_true", help="exit 1 on drift instead of rewriting")
    args = ap.parse_args()

    mj_path = args.root / ".claude-plugin" / "marketplace.json"
    readme_path = args.root / "README.md"
    for p in (mj_path, readme_path):
        if not p.is_file():
            print(f"error: missing {p}", file=sys.stderr)
            return 1

    try:
        plugins = json.loads(mj_path.read_text(encoding="utf-8")).get("plugins", [])
    except json.JSONDecodeError as err:
        print(f"error: {mj_path} is not valid JSON: {err}", file=sys.stderr)
        return 1
    if not plugins:
        # Refuse to blank the table on an empty or unexpected marketplace file:
        # a rendering bug must not look like "the marketplace has no plugins".
        print(f"error: no plugins in {mj_path}", file=sys.stderr)
        return 1

    text = readme_path.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print(f"error: {readme_path} has no {START} / {END} markers", file=sys.stderr)
        return 1

    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    updated = head + render(plugins) + tail

    if updated == text:
        print(f"README table already current ({len(plugins)} plugins)")
        return 0
    if args.check:
        print("README table is STALE — run scripts/render_readme_table.py", file=sys.stderr)
        return 1
    readme_path.write_text(updated, encoding="utf-8")
    print(f"README table regenerated ({len(plugins)} plugins)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
